# Generated by Django 4.2.13 on 2024-05-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
