# Generated by Django 4.2.13 on 2024-05-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0003_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='collection_id',
        ),
        migrations.AddField(
            model_name='blog',
            name='related_collection',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='digitizing_vietnam.collection'),
        ),
    ]
