# Generated by Django 4.2.13 on 2024-05-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0004_remove_blog_collection_id_blog_related_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('blog_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitizing_vietnam.blogtype'),
        ),
    ]
