# Generated by Django 4.2.13 on 2024-05-17 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0005_blogtype_alter_blog_blog_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocr',
            name='document_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitizing_vietnam.document'),
        ),
    ]
