# Generated by Django 4.2.13 on 2024-05-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0006_alter_ocr_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.CharField(default='https://via.placeholder.com/500', max_length=255),
        ),
        migrations.AlterField(
            model_name='ocr',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
