# Generated by Django 4.2.13 on 2024-05-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0007_blog_image_url_alter_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='manifest',
            field=models.TextField(default='{}'),
        ),
    ]
