# Generated by Django 4.2.13 on 2024-05-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0008_document_manifest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocr',
            name='collection_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='digitizing_vietnam.collection'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
