# Generated by Django 4.2.13 on 2024-05-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0009_ocr_collection_id_alter_document_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocr',
            name='collection_id',
        ),
    ]
