# Generated by Django 4.2.13 on 2024-06-03 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0009_ocr_collection_id_alter_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineResourceCategory',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnlineResource',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitizing_vietnam.onlineresourcecategory')),
            ],
        ),
    ]
