# Generated by Django 4.2.13 on 2024-06-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0010_onlineresourcecategory_onlineresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='presentation_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='presentation_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='onlineresourcecategory',
            name='presentation_order',
            field=models.IntegerField(default=0),
        ),
    ]
