# Generated by Django 4.2.13 on 2024-06-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0011_collection_presentation_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineresourcecategory',
            name='image_url',
            field=models.CharField(default='https://via.placeholder.com/500', max_length=255),
        ),
        migrations.AlterField(
            model_name='collection',
            name='presentation_order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='document',
            name='presentation_order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='onlineresourcecategory',
            name='presentation_order',
            field=models.IntegerField(default=1000),
        ),
    ]
