# Generated by Django 4.2.13 on 2024-06-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0012_onlineresourcecategory_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineresourcecategory',
            name='image_url',
            field=models.TextField(default='https://via.placeholder.com/500'),
        ),
    ]
