# Generated by Django 4.2.13 on 2024-07-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0015_rename_category_en_onlineresource_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineresource',
            name='description_vi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlineresourcecategory',
            name='category_name_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onlineresourcecategory',
            name='category_name_vi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='onlineresourcecategory',
            name='description_vi',
            field=models.TextField(blank=True),
        ),
    ]
