# Generated by Django 4.2.13 on 2024-07-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitizing_vietnam', '0016_onlineresource_description_vi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description_vi',
        ),
    ]
